source 'https://rubygems.org'
ruby '2.3.1'

gem 'ffi'
gem 'log4ever'
gem 'parallel_runner'
gem 'mechanize'
gem 'httpclient'
gem 'clockwork'
gem 'twitter', '>=5.0.0'
gem 'tweetstream'
gem 'sys-proctable'
gem 'json'
