source 'https://rubygems.org'
ruby '2.3.1'

ENV['NOKOGIRI_USE_SYSTEM_LIBRARIES'] = 'YES'
gem 'ffi'
gem 'log4ever'
gem 'parallel_runner'
gem 'mechanize'
gem 'httpclient'
gem 'clockwork'
gem 'twitter'
gem 'tweetstream'
gem 'sys-proctable'
gem 'json'
